### ISSUE TITLE
I found this and would be interested in the articles

### ISSUE THREAD

**Issue by zetaron** [naumannt/tf-article#2]
Could you add a `README.md` with links to the articles, that would be awesome :)

**Comment by ImIOImI** [comment]
[Article 1](https://www.esentri.com/building-a-kubernetes-cluster-on-aws-eks-using-terraform)
[Article 2](https://www.esentri.com/building-a-kubernetes-cluster-on-aws-eks-using-terraform_part2)
[Article 3](https://www.esentri.com/building-a-kubernetes-cluster-on-aws-eks-using-terraform-part-iii)
[Article 4](https://www.esentri.com/building-a-kubernetes-cluster-on-aws-eks-using-terraform-part-iv)
[Article 5](https://www.esentri.com/building-a-kubernetes-cluster-on-aws-eks-using-terraform-part-v)

**Comment by naumannt** [comment]
@ImIOImI thank you very much for linking the articles, I didn't have my GitHub notifications set up so I didn't notice the issues.
