### ISSUE TITLE
kubernetes_config_map aws_auth timeout

### ISSUE THREAD

**Issue by ghost** [naumannt/tf-article#3]
I've seen this error:
 
i/o timeout
 
on modules allow_nodes.tf line 17, in resource "kubernetes_config_map" "aws_auth":
  17: resource "kubernetes_config_map" "aws_auth" 

This started happening all of the sudden. I wonder if anybody has seen it.

**Comment by matthewLee711** [comment]
@github4es I'm getting the same issue too. Did you end up figuring out what caused it?

**Comment by matthewLee711** [comment]
Was able to figure out the issue:

depends_on = [ "aws_eks_cluster.tf_eks", "aws_autoscaling_group.tf_eks"] 

Add the above line to your allow_nodes.tf file. Also for anyone in the future who reads this, terraform now has a module that will create your EKS cluster without having to go through this entire process: [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks)

**Comment by naumannt** [comment]
I added the missing depends_on-clause to the article 5-version of the infrastructure. Thanks for the feedback!
