### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Kumar-IND** [naumannt/tf-article#4]
Hi,
I am getting certificate issue,how to resolve it.
PPlease help on this.

Error: Post "https://0964692BCB2AC7F55C5ABBDBC1DD6A70.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps": x509: certificate signed by unknown authority

  on allow_nodes.tf line 17, in resource "kubernetes_config_map" "aws_auth":
  17: resource "kubernetes_config_map" "aws_auth" {

**Comment by naumannt** [comment]
Hmm, I haven't come across this before. Is that error thrown when you try to run 'terraform apply'? It sound like Kubernetes can't trust the certificate that is applied to your node load balancer, leading to the failure while trying to build the config map. 
Are you certain that your certificate(s) are set up properly?

**Comment by Kumar-IND** [comment]
issue resolved.
removed certificate from terraform.
