### ISSUE TITLE
How about fargate

### ISSUE THREAD

**Issue by rustlingwind** [naumannt/tf-article#5]
The series of articles/projects are very great and helpful ! 

Looking forward to the fargate support.

Will the auto scaling group still needed for fargate ?

**Comment by naumannt** [comment]
Fargate does sound like an easier way to set up the node servers indeed. If that is the case, you would indeed use it to replace the autoscaling group and the entire setup around it including the load balancer for the server nodes.
I didn't look into it much before, currently working more on different CI/CD IaC tools like Pulumi. Thanks for mentioning it, I'll look into it in the future.

**Comment by rustlingwind** [comment]
Thanks really, I have been working on EKS fargate recently, Will be honored if can discuss it with you in future.
